version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: realtime-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: realtimemessagesystem
    volumes:
      - mongodb_data:/data/db
    networks:
      - realtime-network

  redis:
    image: redis:7.2-alpine
    container_name: realtime-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - realtime-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: realtime-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - realtime-network

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  realtime-network:
    driver: bridge